# Generated by Django 5.2.4 on 2025-07-20 08:22

from django.db import migrations, models

import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analyst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=30, verbose_name="Topic")),
                ("analyst", models.CharField(max_length=20, verbose_name="Analyst")),
                (
                    "sentiment",
                    models.CharField(
                        blank=True,
                        choices=[("bullish", "Bullish"), ("bearish", "Bearish")],
                        max_length=10,
                        null=True,
                        verbose_name="Sentiment",
                    ),
                ),
                ("text", models.TextField(verbose_name="Text")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=main.models.upload_to,
                        verbose_name="Chart",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Analyst",
                "verbose_name_plural": "Analysts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["analyst"], name="main_analys_analyst_9c12af_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BoughtCoin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coin", models.CharField(max_length=20, verbose_name="Coin")),
                (
                    "bought_price_usdt",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=13,
                        verbose_name="Bought Price USDT",
                    ),
                ),
                (
                    "bought_price_irt",
                    models.IntegerField(verbose_name="Bought Price IRT"),
                ),
                (
                    "sold_price_usdt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=13,
                        null=True,
                        verbose_name="Sold Price USDT",
                    ),
                ),
                (
                    "sold_price_irt",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Sold Price IRT"
                    ),
                ),
                ("usdt_rate_buy", models.IntegerField(verbose_name="USDT Rate (buy)")),
                (
                    "usdt_rate_sell",
                    models.IntegerField(verbose_name="USDT Rate (sell)"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Being Available"),
                ),
                (
                    "profit_usdt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Profit USDT",
                    ),
                ),
                (
                    "profit_irt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Profit IRT",
                    ),
                ),
                (
                    "bought_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Bought At"),
                ),
                (
                    "sold_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sold At"),
                ),
            ],
            options={
                "verbose_name": "Bought Coin",
                "verbose_name_plural": "Bought Coins",
                "ordering": ["-bought_at"],
                "indexes": [
                    models.Index(fields=["coin"], name="main_bought_coin_d2c666_idx"),
                    models.Index(
                        fields=["is_available"], name="main_bought_is_avai_771dde_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntryPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coin", models.CharField(max_length=20, verbose_name="Coin")),
                (
                    "entry_1",
                    models.CharField(
                        help_text="Enter range like: '2.13 - 1.78'",
                        max_length=50,
                        verbose_name="Entry Point 1",
                    ),
                ),
                (
                    "entry_2",
                    models.CharField(
                        blank=True,
                        help_text="Enter range like: '2.13 - 1.78'",
                        max_length=50,
                        null=True,
                        verbose_name="Entry Point 2",
                    ),
                ),
                (
                    "entry_3",
                    models.CharField(
                        blank=True,
                        help_text="Enter range like: '2.13 - 1.78'",
                        max_length=50,
                        null=True,
                        verbose_name="Entry Point 3",
                    ),
                ),
                (
                    "significance",
                    models.CharField(
                        choices=[
                            ("1", "*"),
                            ("2", "**"),
                            ("3", "***"),
                            ("4", "****"),
                            ("5", "*****"),
                        ],
                        max_length=10,
                        verbose_name="Significance",
                    ),
                ),
                ("signal_notes", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=main.models.upload_to,
                        verbose_name="Image",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Entry Point",
                "verbose_name_plural": "Entry Points",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["coin"], name="main_entryp_coin_6ccb46_idx"),
                    models.Index(
                        fields=["significance"], name="main_entryp_signifi_03812a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExitPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coin", models.CharField(max_length=20, verbose_name="Coin")),
                (
                    "exit_1",
                    models.CharField(max_length=50, verbose_name="Exit Point 1"),
                ),
                (
                    "exit_2",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Exit Point 2",
                    ),
                ),
                (
                    "exit_3",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Exit Point 3",
                    ),
                ),
                ("signal_notes", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=main.models.upload_to,
                        verbose_name="Image",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Exit Point",
                "verbose_name_plural": "Exit Points",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["coin"], name="main_exitpo_coin_15c30d_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="MostBoughtCoin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coin", models.CharField(max_length=20, verbose_name="Coin")),
                (
                    "rank",
                    models.IntegerField(blank=True, null=True, verbose_name="Rank"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("1", "TradingView"),
                            ("2", "CoinMarketCap"),
                            ("3", "Cryptometer"),
                        ],
                        max_length=20,
                        verbose_name="Data Source",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Most Bought Coin",
                "verbose_name_plural": "Most Bought Coins",
                "indexes": [
                    models.Index(fields=["coin"], name="main_mostbo_coin_8bb64e_idx"),
                    models.Index(
                        fields=["created_at"], name="main_mostbo_created_c56696_idx"
                    ),
                ],
            },
        ),
    ]
