# Generated by Django 5.2.4 on 2025-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boughtcoin",
            name="bought_price_irt",
        ),
        migrations.RemoveField(
            model_name="boughtcoin",
            name="bought_price_usdt",
        ),
        migrations.RemoveField(
            model_name="boughtcoin",
            name="sold_price_irt",
        ),
        migrations.RemoveField(
            model_name="boughtcoin",
            name="sold_price_usdt",
        ),
        migrations.AddField(
            model_name="boughtcoin",
            name="avg_net_cost_irt",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Bought Price IRT"
            ),
        ),
        migrations.AddField(
            model_name="boughtcoin",
            name="avg_net_cost_usdt",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=13,
                null=True,
                verbose_name="Bought Price USDT",
            ),
        ),
        migrations.AddField(
            model_name="boughtcoin",
            name="holding_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Holding Value",
            ),
        ),
        migrations.AddField(
            model_name="boughtcoin",
            name="total_cost_irt",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Total Cost IRT"
            ),
        ),
        migrations.AddField(
            model_name="boughtcoin",
            name="total_cost_usdt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Total Cost USDT",
            ),
        ),
        migrations.AddField(
            model_name="boughtcoin",
            name="total_earn_irt",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Total Earn IRT"
            ),
        ),
        migrations.AddField(
            model_name="boughtcoin",
            name="total_earn_usdt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Total Earn USDT",
            ),
        ),
    ]
