# Generated by Django 5.2.4 on 2025-07-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_boughtcoin_avg_net_cost_irt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boughtcoin",
            name="avg_net_cost_irt",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="AVG Net Cost (IRT)"
            ),
        ),
        migrations.AlterField(
            model_name="boughtcoin",
            name="avg_net_cost_usdt",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=13,
                verbose_name="AVG Net Cost USDT",
            ),
        ),
        migrations.AlterField(
            model_name="boughtcoin",
            name="holding_value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Holding Value"
            ),
        ),
        migrations.AlterField(
            model_name="boughtcoin",
            name="total_cost_irt",
            field=models.IntegerField(default=0, verbose_name="Total Cost (IRT)"),
        ),
        migrations.AlterField(
            model_name="boughtcoin",
            name="total_cost_usdt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Total Cost (USDT)",
            ),
        ),
        migrations.AlterField(
            model_name="boughtcoin",
            name="total_earn_irt",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Total Earn (IRT)"
            ),
        ),
        migrations.AlterField(
            model_name="boughtcoin",
            name="total_earn_usdt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Total Earn (USDT)",
            ),
        ),
    ]
