# Generated by Django 5.2.4 on 2025-07-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_boughtcoin_avg_net_cost_irt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyst",
            name="analyst",
            field=models.CharField(
                choices=[
                    ("Il Capo", "CryptoCapo"),
                    ("Hayes", "Arthur Hayes"),
                    ("Kiyosaki", "Robert Kiyosaki"),
                    ("Clay", "Alex Clay"),
                    ("Jonathan", "Jonathan Carter"),
                    ("Butterfly", "Butterfly"),
                    ("Noah", "Noah Lutz"),
                    ("", ""),
                ],
                max_length=30,
                verbose_name="Analyst",
            ),
        ),
        migrations.AlterField(
            model_name="boughtcoin",
            name="avg_net_cost_irt",
            field=models.IntegerField(verbose_name="AVG Net Cost (IRT)"),
        ),
        migrations.AlterField(
            model_name="boughtcoin",
            name="avg_net_cost_usdt",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="AVG Net Cost (USDT)"
            ),
        ),
        migrations.AlterField(
            model_name="boughtcoin",
            name="holding_value",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Holding Value"
            ),
        ),
        migrations.AlterField(
            model_name="boughtcoin",
            name="total_cost_irt",
            field=models.IntegerField(verbose_name="Total Cost (IRT)"),
        ),
        migrations.AlterField(
            model_name="boughtcoin",
            name="total_cost_usdt",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Total Cost (USDT)"
            ),
        ),
        migrations.AlterField(
            model_name="boughtcoin",
            name="total_earn_irt",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Total Earn (IRT)"
            ),
        ),
        migrations.AlterField(
            model_name="boughtcoin",
            name="total_earn_usdt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Total Earn (USDT)",
            ),
        ),
        migrations.AlterField(
            model_name="entrypoint",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="entrypoint",
            name="signal_notes",
            field=models.TextField(blank=True, null=True, verbose_name="Signal Notes"),
        ),
        migrations.AlterField(
            model_name="exitpoint",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="exitpoint",
            name="signal_notes",
            field=models.TextField(blank=True, null=True, verbose_name="Signal Notes"),
        ),
        migrations.AlterField(
            model_name="mostboughtcoin",
            name="coin",
            field=models.TextField(verbose_name="Coin"),
        ),
        migrations.AlterField(
            model_name="mostboughtcoin",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="mostboughtcoin",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "TradingView"),
                    ("2", "CoinMarketCap"),
                    ("3", "Cryptometer"),
                ],
                max_length=20,
                null=True,
                verbose_name="Data Source",
            ),
        ),
    ]
