# Generated by Django 5.2.4 on 2025-07-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_mostboughtcoin_coins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mostboughtcoin",
            name="created_at",
            field=models.DateField(verbose_name="Created At"),
        ),
    ]
