# Generated by Django 5.2.4 on 2025-07-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_mostboughtcoin_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boughtcoin",
            name="profit_irt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Profit (IRT)",
            ),
        ),
        migrations.AlterField(
            model_name="boughtcoin",
            name="profit_usdt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Profit (USDT)",
            ),
        ),
    ]
