# Generated by Django 5.2.4 on 2025-07-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_boughtcoin_profit_irt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtcoin',
            name='profit_irt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Profit (IRT)'),
        ),
        migrations.AlterField(
            model_name='boughtcoin',
            name='profit_usdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Profit (USDT)'),
        ),
    ]
