# Generated by Django 5.2.4 on 2025-07-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_mostboughtcoin_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostboughtcoin',
            name='source',
            field=models.CharField(blank=True, choices=[('1', 'TradingView'), ('2', 'CoinMarketCap'), ('3', 'Cryptometer')], max_length=20, null=True, verbose_name='Data Source'),
        ),
        migrations.AlterField(
            model_name='mostboughtcoin',
            name='volume_flow',
            field=models.CharField(choices=[('1', 'Inflow'), ('2', 'Outflow')], default='1', max_length=20, verbose_name='Volume Flow'),
        ),
    ]
