# Generated by Django 5.1.4 on 2025-07-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_entrypoint_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrypoint",
            name="value",
            field=models.CharField(
                blank=True,
                help_text="Enter Value and its worth in USDT: '2000 - 230'",
                max_length=50,
                null=True,
                verbose_name="Value",
            ),
        ),
    ]
