apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: cryptoledger-alerts
  namespace: crypto
spec:
  route:
    receiver: cryptoledger-email
    groupBy: ['alertname', 'severity']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
  receivers:
  - name: cryptoledger-email
    emailConfigs:
    - to: soheil.dalirii@gmail.com
      from: tesla.upload.manager@gmail.com
      smarthost: smtp.gmail.com:587
      authUsername: tesla.upload.manager@gmail.com
      authPassword:
        name: cryptoledger-alert-smtp
        key: password
      requireTLS: true
      sendResolved: true
