# Generated by Django 5.2.4 on 2025-07-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=20, verbose_name='Coin')),
                ('bought_price', models.DecimalField(decimal_places=8, max_digits=13, verbose_name='Min Price')),
                ('sold_price', models.DecimalField(blank=True, decimal_places=8, max_digits=13, null=True, verbose_name='Min Price')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Profit (%)')),
                ('bought_at', models.DateTimeField(auto_now_add=True, verbose_name='Bought At')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='Sold At')),
            ],
            options={
                'verbose_name': 'Bought Coin',
                'verbose_name_plural': 'Bought Coins',
                'indexes': [models.Index(fields=['coin'], name='main_bought_coin_d2c666_idx'), models.Index(fields=['is_available'], name='main_bought_is_avai_771dde_idx')],
            },
        ),
        migrations.CreateModel(
            name='MostBoughtCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=20, verbose_name='Coin')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank')),
                ('source', models.CharField(choices=[('1', 'TradingView'), ('2', 'CoinMarketCap'), ('3', 'Cryptometer')], max_length=20, verbose_name='Data Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Most Bought Coin',
                'verbose_name_plural': 'Most Bought Coins',
                'indexes': [models.Index(fields=['coin'], name='main_mostbo_coin_8bb64e_idx'), models.Index(fields=['created_at'], name='main_mostbo_created_c56696_idx')],
            },
        ),
        migrations.CreateModel(
            name='TargetCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=20, verbose_name='Coin')),
                ('min_target_price', models.DecimalField(blank=True, decimal_places=8, max_digits=13, null=True, verbose_name='Min Price')),
                ('max_target_price', models.DecimalField(blank=True, decimal_places=8, max_digits=13, null=True, verbose_name='Max Price')),
                ('significance', models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], max_length=10, verbose_name='Significance')),
                ('signal_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Target Coin',
                'verbose_name_plural': 'Target Coins',
                'indexes': [models.Index(fields=['coin'], name='main_target_coin_b8d0b4_idx'), models.Index(fields=['significance'], name='main_target_signifi_7a6ce4_idx')],
            },
        ),
    ]
