# Generated by Django 5.2.4 on 2025-07-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_boughtcoin_bought_price_irt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtcoin',
            name='avg_net_cost_irt',
            field=models.IntegerField(blank=True, null=True, verbose_name='AVG Net Cost (IRT)'),
        ),
        migrations.AlterField(
            model_name='boughtcoin',
            name='avg_net_cost_usdt',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=13, null=True, verbose_name='AVG Net Cost USDT'),
        ),
        migrations.AlterField(
            model_name='boughtcoin',
            name='bought_at',
            field=models.DateField(auto_now_add=True, verbose_name='Bought At'),
        ),
        migrations.AlterField(
            model_name='boughtcoin',
            name='profit_irt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Profit (IRT)'),
        ),
        migrations.AlterField(
            model_name='boughtcoin',
            name='profit_usdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Profit (USDT)'),
        ),
        migrations.AlterField(
            model_name='boughtcoin',
            name='sold_at',
            field=models.DateField(blank=True, null=True, verbose_name='Sold At'),
        ),
        migrations.AlterField(
            model_name='boughtcoin',
            name='total_cost_irt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Cost (IRT)'),
        ),
        migrations.AlterField(
            model_name='boughtcoin',
            name='total_cost_usdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Cost (USDT)'),
        ),
        migrations.AlterField(
            model_name='boughtcoin',
            name='total_earn_irt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Earn (IRT)'),
        ),
        migrations.AlterField(
            model_name='boughtcoin',
            name='total_earn_usdt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Earn (USDT)'),
        ),
        migrations.AlterField(
            model_name='boughtcoin',
            name='usdt_rate_buy',
            field=models.IntegerField(verbose_name='USDT Rate (Buy)'),
        ),
        migrations.AlterField(
            model_name='boughtcoin',
            name='usdt_rate_sell',
            field=models.IntegerField(verbose_name='USDT Rate (Sell)'),
        ),
    ]
