# Generated by Django 5.2.4 on 2025-07-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_boughtcoin_avg_net_cost_irt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtcoin',
            name='avg_net_cost_irt',
            field=models.IntegerField(default=0, verbose_name='AVG Net Cost (IRT)'),
        ),
        migrations.AlterField(
            model_name='boughtcoin',
            name='usdt_rate_sell',
            field=models.IntegerField(blank=True, null=True, verbose_name='USDT Rate (Sell)'),
        ),
    ]
