# Generated by Django 5.1.4 on 2026-06-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_entrypoint_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtcoin',
            name='holding_value',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Holding Value'),
        ),
    ]
