apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cryptoledger-tls
  namespace: crypto
spec:
  secretName: cryptoledger-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.host }}
