apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptoledger-media-pvc
  namespace: crypto
  labels:
    app: cryptoledger
spec:
  storageClassName: {{ .Values.persistence.media.storageClass }}
  accessModes:
    - {{ .Values.persistence.media.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
