apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: django-servicemonitor
  namespace: monitoring

  labels:
    release: monitoring

spec:
  namespaceSelector:
    matchNames:
      - crypto

  selector:
    matchLabels:
      monitoring: django

  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
