apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: postgres-exporter
  namespace: monitoring

  labels:
    release: monitoring

spec:
  namespaceSelector:
    matchNames:
      - crypto

  selector:
    matchLabels:
      app: postgres-exporter

  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
    scheme: http
